### ISSUE TITLE
Required Webservice Username and Password

### ISSUE THREAD

**Issue by leifab** [tobania/VSTS.Extension.SqlReportingServices#10]
The code supports using the default credentials by checking for null or blank username and password, however the UI has those marked as required fields.
![capture](https://cloud.githubusercontent.com/assets/3871918/26474614/e6d8a528-4166-11e7-87fb-a111733d4115.png)

**Comment by muziekklas** [comment]
Oh.. don't know why I did that... Ill fix it today

**Comment by muziekklas** [comment]
@leifab  Sorry for the delay (had other projects to do) but I assume this is fixed now. Can you validate it?

**Comment by leifab** [comment]
Confirmed fixed.

**Comment by muziekklas** [comment]
Awesome! Thanks for reporting :)
