### ISSUE TITLE
Add reports to Reporting Services root

### ISSUE THREAD

**Issue by FokkoVeegens** [tobania/VSTS.Extension.SqlReportingServices#11]
Hi,

How to add a report to the root of the report server? It is not allowed to leave the "Upload path" box empty...

Kind regards,
Fokko

**Comment by muziekklas** [comment]
Try using / as the upload path

Op 1 jun. 2017 12:23 p.m. schreef "FokkoVeegens" <notifications@github.com>:

**Comment by FokkoVeegens** [comment]
Thanks, that works!
