### ISSUE TITLE
Resources publishing issue

### ISSUE THREAD

**Issue by PierrickLux** [tobania/VSTS.Extension.SqlReportingServices#13]
Using PowerBi reporting Services over SQL 2016:

When publishing Resources files (such as images), file extension is lost, and MimeType provided in CreateCatalogItem() is not identified as such by RS. Once uploaded, file is recognized as application/octet-stream.

The $fileName provided to CreateCatalogItem should contains the complete FileName (extension included).
``$fileName = [System.IO.Path]::GetFileNameWithoutExtension($_.FullName) + [System.IO.Path]::GetExtension($_.FullName);``

Not sure the best to do it in Powershell :)

Still:, nice Tasks, thank you.

A few additional enhancements:
- Creating Target folder path would be nice to avoid having to create them manually
- Include the rdsFileCount and rsdFileCount as part of the if statement, otherwise we might have an error if path is invalid even though the checkbox is disabled.

**Comment by muziekklas** [comment]
@PierrickLux  Next week I have time to review your issue. (got a few deadlines this week). Ill keep you posted

**Comment by muziekklas** [comment]
@PierrickLux  You can now check the option  _"Add the extension to the resource files"_ in the advanced section.

Can you let me know if this is now resolved (could not test it 100%)

**Comment by muziekklas** [comment]
@PierrickLux FYI, there is a new task, which can deploy the whole folderstructure you have on your local machine :)

**Comment by ygeelen-tb** [comment]
@PierrickLux Is this issue resolved?

**Comment by PierrickLux** [comment]
@ygeelen-tb Yep, perfect thx!
I owe you a beer :)

**Comment by muziekklas** [comment]
@PierrickLux You are welcome.
FYI Our address for the beer is:
Tobania Corda Campus - Gebouw I 
Kempische steenweg 311 box 6.02
3500 Hasselt
