### ISSUE TITLE
No Release task

### ISSUE THREAD

**Issue by fabianre** [tobania/VSTS.Extension.SqlReportingServices#15]
Hi,
I am using the Visual Studio Team Services and added your extension. Unfortunately I am not able to find the task when creating a new build sequence. Did I miss something ?

Thanks,
Fabian

Update:
BTW: Just saw that its clearly writtenin the description, shame on me...
![image](https://user-images.githubusercontent.com/6120885/28367773-678856fe-6c92-11e7-9134-76af7fdb12d5.png)

Unfortunately the release task is also not there.

**Comment by ygeelen-tb** [comment]
Fabian,

It's a task for Release Definitions, not Build Definitions.

**Comment by fabianre** [comment]
Thanks for your fast reply, that make sense. But should I not see it then here ?
![image](https://user-images.githubusercontent.com/6120885/28364068-4b294b44-6c83-11e7-9681-b021ceb0a48c.png)

(Sorry for those dumb questions, just startet to take a look at the whole Team Services topic today)

**Comment by ygeelen-tb** [comment]
Yes you should see it here if the extension is properly installed (the "Deploy" category):
![image](https://user-images.githubusercontent.com/12393883/28364194-ba5dc3a0-6c83-11e7-9eaf-1f1a604e63c4.png)

**Comment by fabianre** [comment]
Hmm unfortunately it does not. Any idea what I can do to resolve it ? I already uninstalled and installed it again without luck.

**Comment by fabianre** [comment]
After uninstall/install again, the tasks now show up. Strange, but luckily sovled.

**Comment by ygeelen-tb** [comment]
We noticed some temporary issue on VSTS or Azure on the extension page. I guess that was it..
