### ISSUE TITLE
System.Management.Automation.ActionPreferenceStopException:The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop

### ISSUE THREAD

**Issue by Kishore10211** [tobania/VSTS.Extension.SqlReportingServices#20]
Hi,
I added the **SqlReportingServicesDeployment** task in VSTS release definition for deploying the reports to the Report Server.

I configured the release definition in VSTS like this below figure.
![s2](https://user-images.githubusercontent.com/17979310/30012311-67a90fea-915c-11e7-9020-1381a4dbc92b.png)

After that, I created release in private agent then I faced the issue like this below:

**System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The HTML document does not contain Web service discovery information.**

Can you please tell me how to resolve this issue as soon as possible?

Regards
Kishore

**Comment by muziekklas** [comment]
Can you post the url (not the serverpart but the path)? I think your used url is wrong (see tooltip for more details)

**Comment by Kishore10211** [comment]
Hi

I gave incorrect web service URL, that's why I am getting above error. by seeing @muziekklas comment then I updated web service URL like this below.
[http://XXXXX/ReportServer_SQLSERVER/ReportService2010.asmx?wsdl](url)

**Comment by muziekklas** [comment]
You're welcome :) A review on the marketplace is appreciated :)
