### ISSUE TITLE
Mislabelled 'Local Dataset path' Field

### ISSUE THREAD

**Issue by philipstratford** [tobania/VSTS.Extension.SqlReportingServices#21]
This could be me getting confused but I believe that the field which should be labelled 'Local Dataset path' is labelled as 'Local Datasource path'. The reasons I believe this to be the case are:

- The field in question appears when the 'Include Data set' checkbox is checked.
- If I check both 'Include data set' and 'Include Data Source', I see two textbox fields labelled 'Local Datasource path', presumably because one is intended to be for the local Data Source path and one is intended to be for the local Dataset path but is mislabelled.

More broadly, the labelling in this extension really needs tidying up. It's completely inconsistent, and when the names of these fields are so similar anyway and there are lots of controls visible on the page, it can get pretty confusing. For example, the extension refers to both "Data Source" and "Datasource", and "Data Set and Dataset". For what it's worth, I believe that the correct terms are "Data Source" (two words) and "Dataset" (one word).

**Comment by muziekklas** [comment]
Thanks for the comment! We will review it and come back with a solution

**Comment by philipstratford** [comment]
I've cloned the repo and fixed the problems with the labels and help text (for the Task that I use, at least). Can you allow me to make a Pull Request?

**Comment by muziekklas** [comment]
@philipstratford You can submit the Pullrequest and we'll review it

**Comment by philipstratford** [comment]
Thanks, that's what I'm trying to do but it says I don't have permission to push changes to the repository. It's possible that I'm not doing it right, I don't use GitHub much.

**Comment by muziekklas** [comment]
@philipstratford Giving you direct access, is not possible. But take a look at the usermanual:
https://help.github.com/articles/about-pull-requests/

**Comment by philipstratford** [comment]
I'd missed the fact that I had to fork the repo first. Pull Request submitted!

**Comment by anton-kirschhock** [comment]
Build succeeded and latest version with your changes is available.
Thanks for the contribution :)
