### ISSUE TITLE
Impossible to set the datasource login identifier.

### ISSUE THREAD

**Issue by Gwenou** [tobania/VSTS.Extension.SqlReportingServices#22]
It is not possible to define a service account user login and password to connect to the datasource, and use the corresponding login option in ssrs.

**Comment by anton-kirschhock** [comment]
Could you provide more information about this issue? It is a bit unclear what you are trying to do

**Comment by anton-kirschhock** [comment]
Closed due to no reponse

**Comment by joemorin73** [comment]
I seem to have the same issue.  When datasources are deployed, there is no option to add Windows Credentials to datasources.  This means all deployments require a manual configuration of the datasources post deployment to add the credentials.
