### ISSUE TITLE
Issue trying to deploy report to sharepoint

### ISSUE THREAD

**Issue by me2there** [tobania/VSTS.Extension.SqlReportingServices#26]
i tried to use both the tasks to deploy to the report library in sharepoint 2016.

**For the  "Deploy SQL server reporting file "** I get "Microsoft.PowerShell.Commands.WriteErrorException: The operation cannot be completed because the file extension is either missing or it is not valid. Valid file extensions include .rdl for report definitions, .smdl for report models, and .rsds for shared dat"
But i see the source folder has right file with rdl extension and even the log says: 

Uploading files
Creating WebService proxy using default credentials
Uploading 1 files to http://

**for "Deploy SQL server reporting folder structure"**  I get 

2017-09-20T20:42:59.4049925Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: The path of the item 'http:/dev.xxxx.xxxx.com/sites/RptCtr/yyyyy' is not valid. The full path must be less than 260 characters long; other restrictions apply. If the report server is in native mode, the path must start with slash. 
I see that the URL is less than 260 characters. URL points to the report library Please help.

**Comment by muziekklas** [comment]
I don't think that sharepoint has any SQL Reporting service.
We do know for a fact that this task works with PowerBI and SQL Reporting services.
