### ISSUE TITLE
VSTS; dont see the new task after intalling

### ISSUE THREAD

**Issue by Manmeetsm** [tobania/VSTS.Extension.SqlReportingServices#31]
After installing SQL Server Reporting Services Deployment from Market place.
I dont see tasks "SQL Server Reporting Services Deployment" in my build scripts.
![image](https://user-images.githubusercontent.com/20839963/31611644-d0cd9a84-b274-11e7-9068-04dd8ead5584.png)

I can see it in my VSTS as installed

![image](https://user-images.githubusercontent.com/20839963/31611682-fe9dbc64-b274-11e7-8433-218d5d71ccfa.png)

**Comment by dancaswell** [comment]
It is a release task only.

**Comment by anton-kirschhock** [comment]
as you said, it is release only

**Comment by Manmeetsm** [comment]
oh thanks. I got it .. cheers
