### ISSUE TITLE
Task Disappears once I refresh the issue

### ISSUE THREAD

**Issue by ghost** [tobania/VSTS.Extension.SqlReportingServices#34]
When I run the build it's working. Once again if I refresh the page and check the task appears and undo button is enabled and if I click it the task is restored. Can you please me to sort this issue..

**Comment by ygeelen-tb** [comment]
Could you describe more in detail what you're trying to do, what the actual result is and what the expected result is? If possible together with screenshots?

**Comment by ghost** [comment]
I will give you step by step process
1. Downloaded VSTS.Extension.SqlReportingServices and installed in TFS server which has a version of TFS2015.Update4.
2.I am sure it's installed as I can see the tasks of SSRS in my build steps.
3.Now I have added "Deploy SQL Server reporting files" task .
4.I have passed all required parameters to the task and saved it.
5.I have run the build and it's successful.
6.After that if I come back again to my build definition the task disappears. It happens only with the additional extensions not with build-in tasks. 
The below image I am adding the task in my TFS
![image](https://user-images.githubusercontent.com/34572994/34043957-005d2bfc-e19b-11e7-99ca-50312deac764.png)
In the below image I am refreshing my browser , the task goes off but the undo button is enabled
![image](https://user-images.githubusercontent.com/34572994/34044049-5e8b229c-e19b-11e7-8b68-797456142090.png)
Once I click the undo button the task is restored.
Something weird.......Please look into this

**Comment by ygeelen-tb** [comment]
We haven't heard about this behavior before, but could you try uninstalling the extension completely and doing a fresh install?

There's nothing exotic about the task, it's a JSON file based on VSTS documentation and a PowerShell script. It's been in use for quite some time by many users.
So perhaps something went wrong during the installation or perhaps there were issues on VSTS/Azure at the time.

**Comment by ygeelen-tb** [comment]
The extension is only tested on VSTS (TFS on Azure) though.
(Although some users have used it on premise as well.)

Perhaps it will work on TFS 2017, but can't make any promises.

**Comment by anton-kirschhock** [comment]
I can only confirm what my collegue said: the task is mainly targetting VSTS (partly tfs 2017). We've not tested it in 2015 and are not maintaining it for TFS 2015.
