### ISSUE TITLE
Verbosing wrong variable?

### ISSUE THREAD

**Issue by austin-best** [tobania/VSTS.Extension.SqlReportingServices#35]
https://github.com/tobania/VSTS.Extension.SqlReportingServices/blob/e6b2de5ff562d0b75ab188a4ed6ac5eeab7e9912/SqlReportingServices/SqlReportingServicesDeployment/SqlReportingServicesDeployment.ps1#L125-L128

is L128 supposed to be `$type`?

**Comment by anton-kirschhock** [comment]
Good one, guess was a rename which we forgot

Op 4 jan. 2018 12:22 schreef "austin-best" <notifications@github.com>:

**Comment by anton-kirschhock** [comment]
Ive reviewed your PR and it will go live at the next deploy
