### ISSUE TITLE
Reports prompts for Log In Name and password

### ISSUE THREAD

**Issue by kathirvel21** [tobania/VSTS.Extension.SqlReportingServices#39]
Currently the add on has the option to overwrite the existing file. it works fine for this option. when we deploy to different folder lets say TEST\ then it is kind of new file upload. After the deployment successful, when we try to open the report, it is asking for the Log In Name and Password. Our report is all set to not to use credentials for the datasource. Eventhough it is, when it is a new file upload it is set to "By prompting the user viewing the report for credentials" on the DataSource of the report. Can you please help me why it is doing it for the new file upload and not for overwrite? Also, I dont see options to delete the report file and upload it again.

**Comment by anton-kirschhock** [comment]
Im not completely understand your issue. Can you attach a screenshot of your vsts configuration?

**Comment by anton-kirschhock** [comment]
Closing due to no response
