### ISSUE TITLE
Can't get Webservice URL to work

### ISSUE THREAD

**Issue by philipstratford** [tobania/VSTS.Extension.SqlReportingServices#4]
Every time, my Release fails with the error: "The HTML document does not contain Web service discovery information." I've tried every variation on the URL for the webservice but can't get it to work.

I've tried the URL that I think really should work, given that it succeeds for deploying from Visual Studio, which is: http://myserver/myreports.

I've also tried:
http://myserver/myreports/myreports.asmx
http://myserver/myreports/myreports.asmx?wsdl

None of these work. My server is definitely being reached because when I used that last URL, the error contained the HTML from the server's error message (saying that the part 'wsdl' didn't exist).

**Comment by philipstratford** [comment]
Figured this out. I needed to use the path:
http://myserver/myreports/reportservice2010.asmx?wsdl

Obviously.

**Comment by ygeelen-tb** [comment]
Hi Philip,

Glad to hear so.
If you hover the info tooltips at the right of each field you will get additional info.
