### ISSUE TITLE
TargetServerVersion

### ISSUE THREAD

**Issue by mchaari** [tobania/VSTS.Extension.SqlReportingServices#43]
Hello,
Is there any option to choose the Target Server Version please ?
Thanks

**Comment by anton-kirschhock** [comment]
Could you be more specific? As far as I am aware the Api is cross version

**Comment by mchaari** [comment]
I developped my reports on VS 2017.
When deploying reports via VS, in Project -> Propeties, I change TargetServerVersion to 2014, to deploy on SQL Server 2014.
In VSTS extension, I don't know if there is an option to do this.
Regards.

**Comment by ygeelen-tb** [comment]
@mchaari what you can do is build your SSRS project in your build definition using MsBuild and specify your BuildConfiguration as MsBuild argument. In your build configuration you can configure the desired TargetServerVersion. Then in your Release Definition you can pick up the artifacts of the build and just deploy them.
![image](https://user-images.githubusercontent.com/12393883/38920006-826eec12-42f2-11e8-992c-b7da363aaa3a.png)

**Comment by mchaari** [comment]
Ok, thanks 👍
