### ISSUE TITLE
SSRS2008

### ISSUE THREAD

**Issue by martin178** [tobania/VSTS.Extension.SqlReportingServices#44]
Is this extension able to deploy against SSRS 2008? I am trying to do it and I receive an error of
Microsoft.PowerShell.Commands.WriteErrorException: Method invocation failed because [Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1er_ReportService2005_asmx_wsdl.ReportingService2005] does not contain a method named 'CreateCatalogItem'.

Thanks

**Comment by anton-kirschhock** [comment]
Looks like the wdsl definition is not correct. Can you provide your configuration? Can you ping from your build agent to your ssrs?

**Comment by martin178** [comment]
Thanks for getting back to me

We have a SSRS 2008 instance. I can ping the server from the build server

This is what we are putting in for the webservice url http://{servername}/ReportServer/ReportService2005.asmx?wsdl

We also have a SSRS 2016 instance where http://{servername}/ReportServer/ReportService2010.asmx?wsdl worked

**Comment by anton-kirschhock** [comment]
In that case, indeed we dont support it. We've developed the tooling in mind with support for ssrs 2k16 or later and never tested the earlier services.
