### ISSUE TITLE
Question: Support for SSRS 2017

### ISSUE THREAD

**Issue by Swellenator** [tobania/VSTS.Extension.SqlReportingServices#50]
Hi 

Does this support SSRS 2017? My understanding is that SSRS 2017 deprecates the WSDL service in favour of a REST API. 

Will this extension still deploy ok?

Thanks

**Comment by ygeelen-tb** [comment]
Is there still a WSDL endpoint available on your 2017 installation? If so, you could give it a try.

**Comment by Swellenator** [comment]
Yes, it looks like there is one. I thought it was being deprecated in favour of the REST API but it is still there. Thanks!
