### ISSUE TITLE
Microsoft.PowerShell.Commands.WriteErrorException: The underlying connection was closed: An unexpected error occurred on a receive. PowerShell script completed with 1 errors.

### ISSUE THREAD

**Issue by alabkrishnan** [tobania/VSTS.Extension.SqlReportingServices#59]

**Comment by alabkrishnan** [comment]
received this error reports partially deployed, not sure what is wrong, any help would be much appricated

**Comment by ygeelen-tb** [comment]
@alabkrishnan if this error has always been there, it could be that you need to allow a different TLS version (SSL).
Or maybe your SQL Server Reporting Server is not accessible from the network you are connecting from.

**Comment by alabkrishnan** [comment]
we were able to solve the issue, the report sizes are large small ones are deployed fine, so we had to change the size to fix the issue

**Comment by ygeelen-tb** [comment]
Thanks for letting us know

**Comment by ndham** [comment]
I am getting this issue but it actually connect to server and in the middle of the publish gives me an error. It already deployed the 10 to 15 reports more . How did you bring the report size smaller?
