### ISSUE TITLE
Unable to Install the extension in TFS 2017

### ISSUE THREAD

**Issue by KrishnaPardhu** [tobania/VSTS.Extension.SqlReportingServices#9]
Hi, 
When I install the extension, it is not available in task catalog. I am using TFS2017. 

Thank you

**Comment by muziekklas** [comment]
Can you share a screenshot please of what you see?

**Comment by KrishnaPardhu** [comment]
After installing the extension I can't see that extension in task catalog. There is nothing in screenshot.

**Comment by muziekklas** [comment]
Did you create a build or release? This task only works in a Release definition.

**Comment by KrishnaPardhu** [comment]
Got it!

Thank you :-)

**Comment by muziekklas** [comment]
Ok you are very welcome!
Also note the little (i) after each field explains a bit what a field is used for.

we are working on documentation (had no time due to projects)

I am closing this
